using System;
using System.IO;
using UnityEngine;
namespace ElementalSandbox
{
    public sealed class SandboxHUD:MonoBehaviour
    {
        public ElementalApp App;
        public bool ShowEditor,ShowHelp=true,ShowMetrics;
        public bool EditingText {get;private set;}
        void Start(){ShowHelp=Screen.width>=900&&Screen.width>Screen.height;}
        GUIStyle title,label,small,button,card,panel,heading;
        Texture2D darkTexture,hoverTexture;
        Vector2 scroll;
        string message="",filter="";
        float scale=1,width,height;
        Rect bar,editor,top,help,metrics;
        bool compact;
        Texture2D[] icons;
        readonly string[] glyphs={"WARD","ACID","GROW","SNAKE","VENOM","RIFT","TIDE","VOID","MARK","REND"};
        void Layout()
        {
            scale=Mathf.Max(.65f,Mathf.Min(Screen.width/1200f,Screen.height/760f));width=Screen.width/scale;height=Screen.height/scale;compact=Screen.width<900||Screen.height>Screen.width;
            float inset=16,barHeight=compact?158:100;bar=new Rect(inset,height-barHeight-inset,width-inset*2,barHeight);top=new Rect(16,16,Mathf.Min(width-32,420),65);editor=new Rect(width-Mathf.Min(350,width-32)-16,94,Mathf.Min(350,width-32),height-barHeight-130);help=new Rect(16,95,330,285);metrics=new Rect(width-310,16,294,ShowMetrics?190:36);
        }
        public bool Blocks(Vector2 p){Layout();Vector2 q=new Vector2(p.x/scale,(Screen.height-p.y)/scale);return bar.Contains(q)||top.Contains(q)||new Rect(16,height-bar.height-64,390,40).Contains(q)||(ShowEditor&&editor.Contains(q))||(ShowHelp&&help.Contains(q))||metrics.Contains(q);}
        void Styles()
        {
            if(title!=null)return;icons=new Texture2D[10];for(int i=0;i<10;i++)icons[i]=Resources.Load<Texture2D>("Elemental/Icons/"+App.Settings.Abilities[i].id);var font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");title=new GUIStyle(GUI.skin.label){font=font,fontSize=20,fontStyle=FontStyle.Bold};title.normal.textColor=new Color(.92f,.96f,1);label=new GUIStyle(title){fontSize=12,fontStyle=FontStyle.Normal,wordWrap=true};small=new GUIStyle(label){fontSize=10};small.normal.textColor=new Color(.6f,.7f,.8f);heading=new GUIStyle(title){fontSize=13};button=new GUIStyle(GUI.skin.button){font=font,fontSize=11,padding=new RectOffset(9,9,8,8)};button.normal.textColor=new Color(.85f,.91f,1);card=new GUIStyle(button){fontSize=13,alignment=TextAnchor.MiddleCenter,wordWrap=true};darkTexture=Rounded(new Color(.045f,.06f,.085f,.9f));hoverTexture=Rounded(new Color(.09f,.12f,.16f,.94f));button.normal.background=darkTexture;button.hover.background=hoverTexture;button.active.background=hoverTexture;button.border=new RectOffset(8,8,8,8);card.normal.background=darkTexture;card.hover.background=hoverTexture;card.active.background=hoverTexture;card.border=new RectOffset(8,8,8,8);panel=new GUIStyle(GUI.skin.box);GUI.skin.font=font;
        }
        static Texture2D Rounded(Color color){var t=new Texture2D(32,32,TextureFormat.RGBA32,false);t.wrapMode=TextureWrapMode.Clamp;for(int y=0;y<32;y++)for(int x=0;x<32;x++){float dx=Mathf.Max(8-x,x-23),dy=Mathf.Max(8-y,y-23);float distance=Mathf.Sqrt(Mathf.Max(0,dx)*Mathf.Max(0,dx)+Mathf.Max(0,dy)*Mathf.Max(0,dy));Color c=color;c.a*=1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(7,8,distance));t.SetPixel(x,y,c);}t.Apply();return t;}
        void OnDestroy(){if(darkTexture!=null)Destroy(darkTexture);if(hoverTexture!=null)Destroy(hoverTexture);}
        void Box(Rect r){Color old=GUI.color;GUI.color=new Color(.06f,.08f,.11f,.94f).linear;GUI.DrawTexture(r,Texture2D.whiteTexture);GUI.color=new Color(.3f,.4f,.52f,.5f).linear;GUI.DrawTexture(new Rect(r.x,r.y,r.width,1),Texture2D.whiteTexture);GUI.color=old;}
        void OnGUI()
        {
            if(App==null||App.Settings==null)return;Layout();Styles();GUI.matrix=Matrix4x4.Scale(Vector3.one*scale);Box(top);GUI.Label(new Rect(30,25,390,28),"ELEMENTAL SANDBOX",title);GUI.Label(new Rect(30,53,390,22),"Select an ability  ·  Aim  ·  Click or tap to cast",small);
            Box(bar);int cols=compact?5:10,rows=compact?2:1;float gap=6,w=(bar.width-20-gap*(cols-1))/cols,h=(bar.height-18-gap*(rows-1))/rows;
            for(int i=0;i<10;i++){Rect r=new Rect(bar.x+10+(i%cols)*(w+gap),bar.y+9+(i/cols)*(h+gap),w,h);Color c=App.Settings.Abilities[i].Color;GUI.backgroundColor=App.Selected==i?Color.Lerp(c,Color.white,.25f):Color.white;if(GUI.Button(r,"",card))App.Select(i);GUI.Label(new Rect(r.x+7,r.y+4,24,18),App.Settings.Abilities[i].key,small);GUI.color=c;if(icons[i]!=null)GUI.DrawTexture(new Rect(r.center.x-16,r.y+8,32,32),icons[i]);GUI.color=Color.white;var caption=new GUIStyle(small){alignment=TextAnchor.MiddleCenter,wordWrap=true};GUI.Label(new Rect(r.x+3,r.y+41,r.width-6,r.height-44),App.Cooldown(i)>0?App.Cooldown(i).ToString("F1")+"s":App.Settings.Abilities[i].label,caption);GUI.color=c;GUI.DrawTexture(new Rect(r.x+5,r.y+r.height-4,r.width-10,2),Texture2D.whiteTexture);if(App.Armed&&App.Selected==i)GUI.DrawTexture(new Rect(r.x+5,r.y+2,r.width-10,2),Texture2D.whiteTexture);GUI.color=Color.white;GUI.backgroundColor=Color.white;}
            float by=bar.y-46;string[] controls={"G  Editor",App.Paused?"P  Resume":"P  Pause","C  Clear","T  Targets","H  Help"};for(int i=0;i<controls.Length;i++){if(GUI.Button(new Rect(16+i*78,by,74,33),controls[i],button)){switch(i){case 0:ShowEditor=!ShowEditor;break;case 1:App.TogglePause();break;case 2:App.Clear();break;case 3:App.ResetTargets();break;case 4:ShowHelp=!ShowHelp;break;}}}
            if(!compact)GUI.Label(new Rect(420,by+8,Mathf.Max(50,width-450),22),App.Status,small);
            Box(metrics);if(GUI.Button(new Rect(metrics.x+8,metrics.y+5,metrics.width-16,26),App.FPS.ToString("F0")+" FPS   ·   "+App.ActiveCount+" / 4 casts   ·   "+(ShowMetrics?"Close":"Metrics"),button))ShowMetrics=!ShowMetrics;
            if(ShowMetrics){GUI.Label(new Rect(metrics.x+14,metrics.y+43,270,76),"CPU update: "+App.CpuMilliseconds.ToString("F2")+" ms\nResolution: "+Screen.width+" × "+Screen.height+"\nRender scale: "+App.ResolutionScale.ToString("P0")+"\nGPU: "+SystemInfo.graphicsDeviceName,label);if(GUI.Button(new Rect(metrics.x+12,metrics.y+125,128,30),"Balanced",button))App.SetQuality(false);if(GUI.Button(new Rect(metrics.x+151,metrics.y+125,128,30),"Economy",button))App.SetQuality(true);GUI.Label(new Rect(metrics.x+12,metrics.y+163,270,20),"Graphics preferences are saved on this device.",small);}
            if(ShowHelp){Box(help);GUI.Label(new Rect(help.x+15,help.y+12,300,24),"CONTROLS",heading);GUI.Label(new Rect(help.x+15,help.y+45,300,232),"Q / E / R / F / V / X / B / Z / N / K\nSelect one of the ten abilities.\n\nMove pointer — aim\nLeft click / tap — cast\nRight drag — orbit camera\nScroll / two-finger pinch — zoom\nTwo-finger drag — orbit on mobile\nEsc / right click — cancel\n\nCircle: ground area    Arrow: line cast\nTargets respawn after being hit.\nPause freezes effects for editing.",label);}
            if(App.Paused){GUI.color=new Color(1,.8f,.35f);GUI.Label(new Rect(width*.5f-75,30,150,30),"PAUSED",title);GUI.color=Color.white;}
            if(ShowEditor)DrawEditor();EditingText=ShowEditor&&GUI.GetNameOfFocusedControl()=="preset";GUI.matrix=Matrix4x4.identity;
        }
        void DrawEditor()
        {
            Box(editor);GUILayout.BeginArea(new Rect(editor.x+12,editor.y+12,editor.width-24,editor.height-24));GUILayout.Label("LIVE VFX EDITOR",heading);GUILayout.Label(App.Settings.Abilities[App.Selected].hint,label);GUILayout.Space(8);GUILayout.BeginHorizontal();if(GUILayout.Button("Save",button))Try(()=>{App.Settings.Save();message="Saved on this device.";});if(GUILayout.Button("Load",button))Try(()=>{App.Settings.Load();message="Preset loaded.";});if(GUILayout.Button("Reset",button)){App.Settings.Reset();message="Artistic defaults restored.";}GUILayout.EndHorizontal();GUILayout.BeginHorizontal();if(GUILayout.Button("Copy JSON",button)){GUIUtility.systemCopyBuffer=App.Settings.Export();message="Preset copied.";}if(GUILayout.Button("Paste JSON",button))Try(()=>{App.Settings.Import(GUIUtility.systemCopyBuffer);message="Preset imported.";});GUILayout.EndHorizontal();if(message.Length>0)GUILayout.Label(message,small);GUILayout.Space(6);GUI.SetNextControlName("preset");filter=GUILayout.TextField(filter);scroll=GUILayout.BeginScrollView(scroll);string id=App.Settings.Abilities[App.Selected].id;
            Slider("global.timeScale","Simulation speed",0,2);Slider("global.glow","Global glow",0,4);Slider("global.particleCount","Particle amount",0,2);Slider("global.particleSize","Particle size",.1f,3);Slider("global.lightIntensity","Light intensity",0,3);Slider("global.cameraShake","Camera shake",0,2);Slider("global.distortion","Refraction",0,3);Slider("camera.distance","Camera distance",3.5f,30);Slider("camera.fov","Field of view",25,80);Slider("camera.autoFrame","Automatic framing",0,.85f);Slider("environment.sunIntensity","Sun intensity",0,5);Slider("environment.ambientIntensity","Ambient light",0,1);Slider("environment.floorPool","Floor light pool",0,1);
            bool texture=App.Settings.B("environment.floorTexture");bool newTexture=GUILayout.Toggle(texture,"Photographic floor texture");if(texture!=newTexture)App.Settings.SetBool("environment.floorTexture",newTexture);
            GUILayout.Space(8);GUILayout.Label("ABILITY",heading);Slider(id+".range","Range",1,40);Slider(id+".speed","Travel speed",1,100);Slider(id+".cooldown","Cooldown",0,12);if(App.Settings.Abilities[App.Selected].zone)Slider(id+".zoneRadius","Area radius",.5f,10);if(id!="cyber")Slider(id+".lifetime","Lifetime",.5f,15);
            switch(id){case "ward":Slider(id+".height","Barrier height",.5f,10);break;case "acid":Slider(id+".mistHeight","Gas height",.5f,12);Slider(id+".mistDensity","Gas density",0,8);break;case "growth":Slider(id+".vineHeight","Vine height",.5f,8);Slider(id+".vineSpread","Vine spread",.1f,1.5f);Slider(id+".bloomHeight","Bloom height",.5f,8);Slider(id+".bloomScale","Bloom size",.2f,5);break;case "cyber":Slider(id+".bodyLength","Serpent length",1,10);Slider(id+".launchHeight","Flight height",.2f,5);Slider(id+".trailLength","Trail length",1,20);Slider(id+".trailWidth","Trail width",.005f,.2f);Slider(id+".trailRadius","Trail radius",.1f,3);break;case "venom":case "quake":Slider(id+".height","Height",.2f,5);Slider(id+".radius","Girth",.1f,2);Slider(id+".width","Path width",.2f,5);Slider(id+(id=="venom"?".gemCount":".stoneCount"),"Geometry count",0,300);Slider(id+(id=="venom"?".burstRadius":".blastRadius"),"Impact radius",.5f,8);Slider(id+(id=="venom"?".burstHeight":".blastHeight"),"Impact height",.5f,5);break;case "ink":Slider(id+".crownHeight","Water crown height",.2f,5);Slider(id+".columnHeight","Water volume height",.2f,6);Slider(id+".wispHeight","Tendril height",.2f,8);break;case "astral":Slider(id+".coreRadius","Event horizon radius",.1f,3);Slider(id+".coreHeight","Event horizon height",.5f,8);Slider(id+".nebulaRadius","Nebula radius",2,14);Slider(id+".shardSpread","Shard spread",.2f,3);break;case "cascade":Slider(id+".crownHeight","Crown height",.5f,8);Slider(id+".crownScale","Crown size",.2f,4);Slider(id+".wispHeight","Wisp height",1,8);Slider(id+".bladeWidth","Blade width",.01f,.25f);break;case "rend":Slider(id+".pillarHeight","Pillar height",5,40);Slider(id+".pillarRadius","Pillar radius",.05f,1);Slider(id+".chargeTime","Charge duration",.2f,5);Slider(id+".starSize","Star size",.2f,5);Slider(id+".haloRadius","Halo radius",.2f,5);break;}
            GUILayout.EndScrollView();GUILayout.EndArea();
        }
        void Slider(string key,string name,float min,float max){if(filter.Length>0&&name.IndexOf(filter,StringComparison.OrdinalIgnoreCase)<0&&key.IndexOf(filter,StringComparison.OrdinalIgnoreCase)<0)return;float value=App.Settings.F(key);GUILayout.BeginHorizontal();GUILayout.Label(name,small);GUILayout.FlexibleSpace();GUILayout.Label(value.ToString("0.##"),small,GUILayout.Width(45));GUILayout.EndHorizontal();float next=GUILayout.HorizontalSlider(value,min,max);if(Mathf.Abs(next-value)>.00001f)App.Settings.Set(key,next);}
        void Try(Action action){try{action();}catch(Exception e){message=e.Message;}}
    }
}
